version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - 5432:5432
  api:
    image: api:dev
    build:
      dockerfile: Dockerfile.dev
      context: ./
    depends_on:
      - db
    volumes:
      - /node_modules
      - ./:/app
    ports:
      - 4000:4000