apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: your-domain-tls
spec:
  secretName: your-domain-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: your-domain.com
  dnsNames:
    - your-domain.com
    - www.your-domain.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - your-domain.com
          - www.your-domain.com
