apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate-tls
spec:
  secretName: {{ .Values.domainAsName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.domain }}
  dnsNames:
    - {{ .Values.domain }}
    - {{ .Values.wwwDomain }}
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - {{ .Values.domain }}
          - {{ .Values.wwwDomain }}
