apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-modsecurity-crs: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDebugLog /tmp/modsec_debug.log
spec:
  tls:
    - hosts:
        - {{ .Values.domain }}
        - {{ .Values.wwwDomain }}
      secretName: {{ .Values.domainAsName }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: {{ .Values.serverPort }}
    - host: {{ .Values.wwwDomain }}
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: {{ .Values.serverPort }}
