apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: {{ .Values.serverReplicas }}
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: {{ .Values.serverDockerImage }}
          ports:
            - containerPort: {{ .Values.serverPort }}
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: {{ .Values.dbPort }}
            - name: PGDATABASE
              value: {{ .Values.dbName }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '1Gi'
              cpu: '1'
